### ISSUE TITLE
Crash when trying to crack egg yolk into a bowl with egg whites.

### ISSUE THREAD

**Issue by nicksal21** [GastronomistGuild/ACulinaryArtillery#22]
To reproduce the error:
1. Partially crack an egg so that there is 0.1L of egg whites in a bowl
2. Crack the remaining egg yolk into said bowl.
3. Crash-to-desktop:
```
Running on 64 bit Windows 10.0.19045.0 with 16331 MB RAM
Game Version: v1.19.4 (Stable)
3/15/2024 10:28:48 PM: Critical error occurred in the following mod: aculinaryartillery@1.0.16
Loaded Mods: aculinaryartillery@1.0.16, chiseltools@1.10.2, claycasting@1.1.5, geodesandgemstones@1.1.0, geoaddons@1.3.3, hammercrushed@1.0.0, HangingOilLamps@1.0.1, healthiertrees@1.0.0, millwright@1.1.4, natshumanskin@1.0.0, oils@1.0.1, peacockbasses@1.1.2, primitivesurvival@3.4.6, she1fish@1.2.0, sortablestorage@2.2.1, spyglass@0.5.0, thecritterpack@0.8.6, translocatorengineeringredux@1.4.9, volumetricshadingreupdated@0.7.5, game@1.19.4, wlts@1.0.0, alchemy@1.6.25, beehivekiln@1.5.1, betterfirepit@1.1.4, canjewelry@0.2.11, carryon@1.7.4, clrd@1.0.0, coinage@1.10.1, commonlib@2.3.0, composter@1.1.0, cropseedstage@1.0.1, debarkedlogintofirewood@1.0.0, earlychiseling@1.0.1, expandedfoods@1.6.8, farmlanddropssoil@1.4.0, fishing@1.1.5, flowerfarming@1.0.0, hudclock@3.4.0, sailboat@1.2.8, jopainting@1.4.0, knapster@2.7.1, lavoisier@1.3.0, moreanimals@1.3.3, nemi@1.1.0, petai@2.2.3, rivers@2.5.0, simpleconcrete@1.0.1, simpleemotemenu@1.1.0, simplestep@1.1.6, stickemup@1.1.0, stonebakeoven@1.1.3, tablet@0.1.4, terrapretatrade@1.0.0, vtpp@1.1.1, creative@1.19.4, vsinstruments@1.2.7, survival@1.19.4, wildfarmingrevival@1.1.7, workbenchexpansion@1.8.0, bullseye@2.5.3, chemistrylib@1.1.5, em@2.5.0, gespileslib@1.2.0, stonequarry@3.2.1, wolftaming@2.1.0, bricklayers@2.5.0, tailorsdelight@1.3.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemEggCrack.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 854
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by l33tmaan** [comment]
Try downloading the 1.2.2 update and let me know if this still happens.

**Comment by Ymmats** [comment]
This still happens ill post my crash log once i do

**Comment by l33tmaan** [comment]
I can't replicate this anymore. Is it still happening in ACA 2.0.0-dev.18?

**Comment by l33tmaan** [comment]
This definitely shouldn't be happening in 2.0.0-dev.22. I'm closing this out, please open a new report if it happens again.
